### ISSUE TITLE
Redundant exception handling

### ISSUE THREAD

**Issue by poliakhd** [AlexanderKononenko210b/Mentoring.L1.2018.IntroductionTo.Net#2]
https://github.com/AlexanderKononenko210b/Mentoring.L1.2018.IntroductionTo.Net/blob/09d2ff5041c37376b3bce747480ae6c326e14b2b/ModuleVS/CoreApp/Program.cs#L24-L35

Если у тебя нет особой логики для каждого типа исключений, зачем дублировать код? Можно оставить обработчик для **Exception e** и будет работать так же.

**Comment by AlexanderKononenko210b** [comment]
Исправлено.
