### ISSUE TITLE
args[] reduntant null checking

### ISSUE THREAD

**Issue by poliakhd** [AlexanderKononenko210b/Mentoring.L1.2018.IntroductionTo.Net#3]
https://github.com/AlexanderKononenko210b/Mentoring.L1.2018.IntroductionTo.Net/blob/09d2ff5041c37376b3bce747480ae6c326e14b2b/ModuleVS/CoreApp/Program.cs#L12-L15

**string[] args** никогда не будет null, так что проверка избыточна.

**Comment by AlexanderKononenko210b** [comment]
Исправлено.
