### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by poliakhd** [AlexanderKononenko210b/Mentoring.L1.2018.IntroductionTo.Net#4]
https://github.com/AlexanderKononenko210b/Mentoring.L1.2018.IntroductionTo.Net/blob/09d2ff5041c37376b3bce747480ae6c326e14b2b/ModuleVS/ModuleStandart/Greeting.cs#L22-L24

Не сказал бы что issues, просто хочу чтобы обратил внимание. Не вижу чтобы **currentTime** использовался бы потом где-либо, так что здесь вполне бы лучше смотрелось:

**return $"{DateTime.Now.TimeOfDay} Hello {name}";**

**Comment by AlexanderKononenko210b** [comment]
Исправлено.
